### PR TITLE
Fix Flow errors

### PR DESCRIPTION
**Pull request by hadim**
Flow errors down to 25 so far.

WIP, DO NOT MERGE.

The deployed instance at https://shinkgs-flow-fixes.now.sh should be tested for any regressions.

### CODE REVIEW

**Comment by hadim** [comment]
Flow errors down to 19.

@jkk I need you for couple of Flow errors I can't fix myself. I am pretty new to JS/React so any comments would be super useful.

- In [tree.js](https://github.com/jkk/shinkgs/blob/57991a204e4aed550d0f900ce5082010d74d985a/src/model/game/tree.js#L133), Flow says that `rulesProp` does not have properties such as `size` and `mainTime`. According to Flow `rulesProp` should be of type `Sgfprop` that does not have those properties. I found that those properties are present in `GameRule` (in `type.js`). What is the real type of `rulesProp`? I guess it's `GameRule`.

- In [`GameInfo.js`](https://github.com/jkk/shinkgs/blob/master/src/ui/game/GameInfo.js#L80): Flow complains:

```
Cannot create `tbody` element because in type argument `Yield` [1] of the return value of property `children.@@iterator`:
 - Either inexact object type [2] is incompatible with exact `React.Element` [3].
 - Or object type [2] is incompatible with `React.Portal` [4].
 - Or property `@@iterator` is missing in object type [2] but exists in `$Iterable` [5].
 ```

 No idea how to fix that.

 - All the remainings messages are:

 ```
 Cannot create `div` element because `HTMLElement` [1] is incompatible with null [2] in the first argument of property `ref`.
 ```

 Here again, any help to fix it would be appreaciated.

**Comment by hadim** [comment]
Once all the Flow errors are gon, I will enable the Flow check in Travis and merge this PR.

**Comment by hadim** [comment]
All errors are now gone except for the one related to `rulesProp` in `tree.js`.

**Comment by jkk** [comment]
@hadim using the `Node` type from React may help you type children and other content inserted into JSX. The Flow docs have more info: https://flow.org/en/docs/react/

Btw maybe types like `?string` are exactly equivalent to `string | null | undefined`. See https://flow.org/en/docs/types/maybe/. Most of the ref errors can probably be solved by using maybe time for the ref and places where it's taken as an argument.

For rulesProp, I'm not sure off hand, I don't remember. I'd have to look more deeply which I don't have time for at the moment.

**Comment by hadim** [comment]
Thank you for the help. Yes, you're right, using `?` or `| null` fixed most fo the issues.

I'll try to investigate more about the `rulesProp`.

**Pull request merged**
