### PR TITLE
"Game Info" option added to "More" menu

### PR DESCRIPTION
**Pull request by beejunk**
This resolves issue #115.

Items that currently have been added to the Game Info modal include everything in the GameInfo component, plus: board size, game ID, time, and place. 

To view the proposed changes, see the Now deployment at:

https://shinkgs-server-myiyhwtpsn.now.sh

Just log in and view any game. Then open the More menu and select Game Info.

### CODE REVIEW

**Comment by beejunk** [comment]
It looks like that previous Now deployment stopped working, so I've set up a new one here:

https://shinkgs-server-moidbyglgp.now.sh

Also, in case that deployment fails, here is a screen shot of the proposed changes:

shingkgs_screenshot

**Comment by beejunk** [comment]
I spent some time looking through the KGS API documentation and discovered that there is indeed a reference for the property names that KGS uses. I'm going to go ahead and work up another commit that incorporates more of those properties.

**Comment by beejunk** [comment]
Okay, new commit has been added. Here's an updated now deployment:

https://shinkgs-server-wrjdhrdlmx.now.sh

**Comment by beejunk** [comment]
Added another commit with a couple additional fixes. Now deployment is here:

https://shinkgs-server-qwgqklllgt.now.sh

Here is a screen shot of a demo game I set up using all the possible fields:

shingkgs_screenshot_2

**Comment by jkk** [comment]
This is looking great! I hope to be able to give it a look over and merge this weekend.

**Comment by beejunk** [comment]
Whoops, I just noticed I doubled up on the game name. I'll get a commit in to fix that some time this evening.

**Comment by beejunk** [comment]
I'm new to git and still getting used to appropriate workflows, and I realize now I should've created my own branch for this change so that I can work on other issues as well. I'm going to close this pull request and set get my fork set up more appropriately, and then I will issue the pull request again.

**Pull request closed without merging**
