### PR TITLE
Sort users in game screen

### PR DESCRIPTION
**Pull request by mikach**
Closes https://github.com/jkk/shinkgs/issues/69

### CODE REVIEW

**Comment by jkk** [comment]
Did you notice if this has any perceptible effect on render time? I was a bit concerned about sorting a large list of users every render, especially on mobile devices, but I didn't actually measure or try it.

**Comment by jkk** [comment]
(FYI I am out of town with limited computer access for a few days so I can't try it myself. If you determine the sort doesn't meaningfully affect render time I'll go ahead and merge it.)

**Comment by mikach** [comment]
I didn't check, but I don't think sorting an array would affect performance somehow.

**Comment by jkk** [comment]
It's not a question of whether it affects perf (it does), but how much. On a low end device, sorting a large list of users can take around 10ms. Sorting a subset of game users will be much faster. So it's ok for now - going to merge.

**Pull request merged**
