### PR TITLE
Fix issue #11 - Load archive game

### PR DESCRIPTION
**Pull request by beejunk**
Here's an initial attempt at loading archived games. I'm definitely not sure if I've taken the right approach to this, so any and all input from @jkk  is welcome.

One thing to note is that current versions of Flow expect component state and prop types to be passed in the class declaration like so:

```typescript
export default class GameSummaryList extends Component<Props, State> {
  // ...
}
```
I went ahead and did this with the some of the classes I worked on, which appeases Flow but makes them different from the rest of the code base. Let me know if you prefer that I stick with the old way.

Here's a *now* deployment:

https://shinkgs-server-bkjcylsgay.now.sh

### CODE REVIEW

**Comment by beejunk** [comment]
Congratulations, and enjoy your honeymoon!

**Comment by hadim** [comment]
@beejunk  could you rebase your PR to the current master so I can review it?

The recent master got a lot of fixes to upgrade to React 16 and make flow *almost* happy (only 45 errors remain). I fixed all the component state and prop types (manually....).

**Comment by beejunk** [comment]
Will do. I'll try to get to that some time tonight.

Thanks for working on this!

**Comment by beejunk** [comment]
Okay, I've done a rebase and published a new `now` deployment, which can be found here:

https://shinkgs-mwdcjacbmn.now.sh

As I mentioned in my initial comment, I'm not too sure if this is the right way to approach this issue. In particular, the loading of the archived game often takes a few seconds, and currently there's no indication that anything is happening  (i.e., no loading spinner). Any and all criticisms/recommendations are welcome.

**Comment by hadim** [comment]
@beejunk Thank you for doing this, it looks great. I did a quick test and it looks good to me. Maybe we should wait a few more days before merging so other people can report bugs or regressions.

Also, I should tell you and @jkk that I started rewriting ShinKGS from scratch using Material UI and Redux as well as reusing Go related Javascript libraries such as https://github.com/SabakiHQ/shudan-goban. The code is closed source for now but will be opened once I got something working.

@jkk Don't take it wrong, what you've built is truly amazing but after spending some time reading at the code, I had difficulties modifying the interface mostly because of the CSS. That's why I like to use a third-party library such as Material UI that abstract UI and let designer creating a theme allowing almost-fully customization of the interface without touching the source code. The use of Redux is mainly to be able to use a standard allowing eventual code contributors to easily understand the code and start contributing (but I might be naive here, future will tell).

At the moment, I probably won't work on this repo much focusing on my "fork". I know it's an ambitious work so there are chances for it to fail, in that case I will eventually start working on this repo again. 

Hope you guys understand.

**Comment by hadim** [comment]
About this PR, I would be happy to merge it in few days.

**Comment by beejunk** [comment]
Closing this out. It's been a while and I'm guessing this PR is no longer needed.

**Pull request closed without merging**
