### PR TITLE
Add contribute button + upgrade to React 16 + various fixes

### PR DESCRIPTION
**Pull request by hadim**
Add a contribute button next to the feedback button.

screenshot from 2018-09-08 12-38-57

Upgrade deps to latest + upgrade to React 16.

### CODE REVIEW

**Comment by jkk** [comment]
Awesome! Does it work on tablet/mobile sizes? I'll give it a test run when I get a chance this weekend

**Comment by hadim** [comment]
Last commit add Travis + fix various lint errors.

Do not merge yet please.

**Comment by hadim** [comment]
@jkk I have fixed almost all the Flow errors (mostly due to the React 116 upgrade I think). 47 errors are remaining and are probably more tricky to fix.

I think this PR is good for review + merge.

I also enabled Travis that I'll prevent people from pushing code that doesn't pass the lint+flow checks and should help code maintenance in the future. Note for now the flow check is disabled in the Travis file because of the remaining errors I didn't fix yet.

I am ok to see this PR merged before fixing the remaining errors. 

For the next time I'll do a better job keeping PR smaller and avoid mixing different things together, I did it that way because I wanted to continue building on my previous commits.

**Comment by hadim** [comment]
Once we're done with this one, I'll start working on easy issue: https://github.com/jkk/shinkgs/issues?q=is%3Aopen+is%3Aissue+label%3A%22difficulty%3A+starter%22

**Comment by jkk** [comment]
This is a pretty huge set of changes. Normally I'd prefer things be broken up, but you seem to know what you're doing, so I'm inclined to accept and let things get iterated. A few thoughts:

1) You did lots of reformatting. Did you use prettier or something else? I'd like to have prettier integration built in. I usually create a yarn shortcut for that to make it easier for contributors.

2) This may invalidate other open PRs that I haven't had a chance to review. Most of them are small so maybe it won't be difficult to update them.

3) Have you tried deploying this to now.sh? You don't need special permission to do so, it should just work with the KGS API if you follow the readme instructions (I think).

I'll take another look later tonight after dinner.

**Comment by jkk** [comment]
Oh: and thanks for taking the initiative! Pretty awesome to see people jump in. 👍 👍

**Comment by hadim** [comment]
Yes sorry for the mess. I'll promise to do smaller PRs in the future. I used vscode with the prettier extension. Maybe we could add a yarn shortcut so people that don't use prettier can still autoformat the code easily.

You're right it could invalidate other PRs and that's a pretty bad thing... I don't really know how to deal with that. Or we wait for you to review the other PRs before merging this one (after a proper rebase). Or we first merge this one and update the other ones. If they are small that should be as easy as you said.

I didn't try to deploy to now.sh. I'll try later.

**Comment by hadim** [comment]
Wow now.sh is pretty awesome!

I got Travis to deploy every single commit to now.sh and then create an alias with the name of the branch the commit is built on. So for this PR you can see the build live at: https://shinkgs-contribute.now.sh/

And all of this is fully automatic. You only need to set a variable `NOW_TOKEN` in the Travis configuration.

It will be super easy to deploy automatically each Git tagged release to the official shinkgs URL. But let's do that later once this PR is merged.

**Comment by hadim** [comment]
@jkk Bad news, Travis disable deployment on pull requests. So deployment will only happen on commits from this repo (master branch and the other ones).

For this reason, I might create new branches on this repo to open pull requests instead of my private repo.

For external contributions, I think we can just ask people to deploy themselves or test it yourself locally.

**Comment by hadim** [comment]
Ok. The monster has been merged.

**Comment by hadim** [comment]
Let's see if master gets deployed.

**Comment by jkk** [comment]
@hadim zeit.co has their own github integration too that might be helpful? I haven't looked at it very closely so not sure - https://zeit.co/blog/now-for-github

**Comment by hadim** [comment]
Interesting. It seems to deploy PRs too. It's not a priority but I will have definitively have a look soon.

**Pull request merged**
