### PR TITLE
Allow room selection on challenge creation form

### PR DESCRIPTION
**Pull request by dnp87**
Remake of PR #169 and some Flow work. Most of credits goes to sartak, author of original PR.

### CODE REVIEW

**Comment by leeschumacher** [comment]
ok, deployed to shin.gokgs.com.

**Comment by shimari65** [comment]
@dnp87 Thanks so much for writing this addition, sorry it has been over a year since it was done and we are only deploying it now!  The AGF is now running KGS, and we are hosting ShinKGS and working on that too. We are hoping to make lots of improvements to Shin, and relying on our users to help us with that.  Your module adds more fo the main rooms, but still doesn't add any of the sub categories, like Social, Clubs, or Tournaments, all of which are important for people who want to use custom rooms. Would you be willing to add that feature in when you get a chance?  Thanks so much, Paul Barchilon, AGF Vice-President.

**Comment by dnp87** [comment]
@shimari65, thanks for the feedback, but I can't guarantee anything at the moment.

**Comment by shimari65** [comment]
@dnp87 actually I just tried it again and it works.  It seems to pull up rooms there are people in, so as long as you are in the room you want to launch a game in, the room shows up on the list.  That should work just fine.  Thanks for writing this!

**Pull request merged**
